use_frameworks!
swift_version = '5.0'

def core_libs
  pod 'KeePassCore', :path => '../'  
end

def rx_libs
  pod 'RxCocoa', '~> 5.0.0'
  pod 'RxSwift', '~> 5.0.0'  
end

def app_libs
  pod 'SwiftLint', '~> 0.34.0'
  pod 'Swinject', '~> 2.6.2'

  pod 'RxDataSources', '~> 4.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  pod 'DiffableDataSources'
end

def google_libs
  pod 'GoogleAPIClientForREST/Drive', '~> 1.3.10'
  pod 'GoogleSignIn', '~> 5.0.2'
end

target 'iOSApp' do
  platform :ios, '12.0'
  core_libs
  rx_libs
  google_libs
  app_libs
end

target 'Pods_Tests' do
  pod 'Swinject', '~> 2.6.2'
  core_libs
  rx_libs
  google_libs
  platform :ios, '12.0'  
  inherit! :search_paths
end

target 'iOSAppAcceptanceTests' do
  core_libs
  platform :ios, '12.0'  
  inherit! :search_paths
end

target 'MacApp' do
  platform :osx, '10.11'
end

target 'MacAppTests' do
  platform :osx, '10.11'  
  inherit! :search_paths
end
